apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-medicos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-medicos
  template:
    metadata:
      labels:
        app: ms-medicos
    spec:
      containers:
        - name: ms-medicos
          image: jean1988/ms-medicos:1.0
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: ms-medicos-config
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9092
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9092
            initialDelaySeconds: 15
            periodSeconds: 10