apiVersion: v1
kind: Service
metadata:
  name: ms-medicos-service
spec:
  selector:
    app: ms-medicos
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30992
  type: NodePort